import type { Metadata } from "next";
import "../styles/globals.css";
import { Providers } from "../provider/chakraProvider";
import { fonts } from "../utils/fonts";
import Navbar from "@/components/home/sections/navbar";

export const metadata: Metadata = {
  title: "Ari Connect",
  description: "Generated by create next app",
  icons : {
    icon: [
      '/favicon.ico?v=4',
    ],
    apple: [
      '/apple-touch-icon.png?v=4'
    ],
    shortcut: [
      '/apple-touch-icon.png'
    ]
  },
  manifest: '/site.webmanifest'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.inter.variable}>
      <body>
        <Providers>
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
